name: CI -> Deploy to My website
on:
  push:
    branches: [ main ]
env:
    # Setting an environment variable with the value of a configuration variable
    env_var: ${{ vars.ENV_CONTEXT_VAR }}    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # debug
      - name: Checkout sources
        run: |
            echo test debug
            echo "test debug"
            echo "${{ secrets.FTP_SERVER }}"
            echo "${{ secrets.FTP_USERNAME }}"
            echo "${{ secrets.FTP_PASSWORD }}"
            echo "${{ vars.DEBUG_ABC }}"

      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./docs"
          remote_dir: "/docs"
          delete: "true"
          ftp_ssl_allow: "false"
